#### general settings
name: 001_EDVRwoTSA_comb_lr4e-4_600k_youku_LrCAR4S
use_tb_logger: true
model: video_base
distortion: sr
scale: 4
gpu_ids: [4]

#### datasets
datasets:
  train:
    name: youku
    mode: youku
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: /media/tclwh2/public/youku/train/gt
    dataroot_LQ: /media/tclwh2/public/youku/train/lq
    # dataroot_x2GT: /media/tclwh2/public/youku/train/x2gt
    # dataroot_x2LQ: /media/tclwh2/public/youku/train/x2lq
    cache_keys: ~

    N_frames: 5
    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 16
    GT_size: 256
    LQ_size: 64
    use_flip: true
    use_rot: true
    down_sample: false
    color: RGB
  val:
    name: youku
    mode: video_test
    dataroot_GT: /media/tclwh2/public/youku/val/gt
    dataroot_LQ: /media/tclwh2/public/youku/val/lq
    cache_data: True
    N_frames: 5
    padding: new_info

#### network structures
network_G:
  which_model_G: EDVR
  nf: 64
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: false
  HR_in: false
  w_TSA: false
  block_type: rcab

#### path
path:
  pretrain_model_G: ../experiments/001_EDVRwoTSA_comb_lr4e-4_600k_youku_LrCAR4S/models/150000_G.pth
  strict_load: true
  resume_state: ../experiments/001_EDVRwoTSA_comb_lr4e-4_600k_youku_LrCAR4S/training_state/150000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 300000
  warmup_iter: -1  # -1: no warm up
  T_period: [150000, 150000]
  restarts: [150000]
  restart_weights: [1]
  eta_min: !!float 1e-7

  pixel_criterion: comb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
